from numpy import *
x=input().split()
a=float(x[0])
b=float(x[1])
y=input().split()
c=double(y[0])
d=double(y[1])
print('A = {0:.6f}, B = {1:.6f}'.format(a,b))
print('C = {0:.6f}, D = {1:.6f}'.format(c,d))
print('A = {0:.1f}, B = {1:.1f}'.format(a,b))
print('C = {0:.1f}, D = {1:.1f}'.format(c,d))
print('A = {0:.2f}, B = {1:.2f}'.format(a,b))
print('C = {0:.2f}, D = {1:.2f}'.format(c,d))
print('A = {0:.3f}, B = {1:.3f}'.format(a,b))
print('C = {0:.3f}, D = {1:.3f}'.format(c,d))
print('A = {0:.3E}, B = {1:.3E}'.format(a,b))
print('C = {0:.3E}, D = {1:.3E}'.format(c,d))
print('A = {0:.0f}, B = {1:.0f}'.format(a,b))
print('C = {0:.0f}, D = {1:.0f}'.format(c,d))
